baseURL = 'https://goldengatesoftwaresolutions.com/'
languageCode = 'en-us'
title = 'Jackson the Tech Guy'

[menus]

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 30

[[menus.main]]
name = "Blog"
pageRef = "/blog"
weight = 30

[[menus.main]]
page = "Services"
pageRef = "/"
weight = 10
[menus.main.params]
sectionId = "services"

[outputformats]
[outputformats.gohtml]
mediaType = "text/html"
baseName = "index"
isHTML = true

[params]
[params.contact]
email = "jackson@goldengatesoftwaresolutions.com"
phone = "+14157613680"
